secret:
  telegramToken: ${TELEGRAM_TOKEN}
  chat_id: ${CHAT_ID}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Musinsa-Stock-Notification-Bot
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    show-sql: true